### ISSUE TITLE
authz support

### ISSUE THREAD

**Issue by tac0turtle** [ChihuahuaChain/chihuahua#15]
add authz support and coordinate an upgrade. 

happy to help with adding it.

**Comment by faddat** [comment]
If we were to upgrade the puppy, authz is a great idea.

**Comment by tac0turtle** [comment]
happy to make a pr adding it too!

**Comment by must479** [comment]
How to deploy

**Comment by jemrickrioux** [comment]
We are currently doing a testnet to make sure we can upgrade smoothly

**Comment by ChihuahuaChain** [comment]
Authz will be implemented on the next chain upgrade
